export const SET_REDDIT_COMMENTS = 'SET_REDDIT_COMMENTS';
export type SET_REDDIT_COMMENTS = typeof SET_REDDIT_COMMENTS;

export const RESET_REDDIT_COMMENTS = 'RESET_REDDIT_COMMENTS';
export type RESET_REDDIT_COMMENTS = typeof RESET_REDDIT_COMMENTS;

export const SET_REDDIT_POSTS = 'SET_REDDIT_POSTS';
export type SET_REDDIT_POSTS = typeof SET_REDDIT_POSTS;
